host = "127.0.0.1"
port = 3000
telegram_bot_token = "" # define in .secrets.toml
telegram_webhook_host = "" # define in .secrets.toml
telegram_webhook_path = "" # define in .secrets.toml
admin_token = "" # define in .secrets.toml