host = "127.0.0.1" #
port = 3000
# The following settings should be specified either in .secrets.toml file
# or provided as environment variables:
# telegram_bot_token = "" # Bot token provided by @BotFather.
# telegram_webhook_host = "" # Publicly accessible bot server host. Used by Telegram to send updates to bot.
# telegram_webhook_path = "" # Bot endpoint path. Used by Telegram to send updates to bot.
# admin_token = "" # Bot administrator token (password).
# database_url = "" # URL of the bot database.